### ISSUE TITLE
Subtitles for manually downloaded movies and series?

### ISSUE THREAD

**Issue by notDavid** [Jonybat/flexget_config#10]
Hi, i have a question i was hoping you could help me with;

would it be possible with some minor adjustments to also download subtitles for the movies (& series) that i manually download into the "/{{secrets.folder.root}}{{secrets.folder.downmovies}}" folder?

(what your config already does is nicely rename these folders/files and move them to "/{{secrets.folder.root}}{{secrets.folder.movies}}"... )

**Comment by Jonybat** [comment]
Hi. The task that moves the movies (and series) from the folder.downxxx to the respective folder also adds the movie/episode to the subtitle queue that will then download the subtitles to the final destination. So, if I understand your question correctly, it is already working as you want :)

**Comment by notDavid** [comment]
thanks for your reply. Okay i see, the problem is that i am not seeing any subtitles for manually downloaded files.
I checked the log file now and i think the problem is that Flexget first moves the files to the final destination, and then after that tries to download the subtitles from the old location, but fails because the files no longer exist there;

```
2016-11-27 13:17 INFO     move          move-movies     `/home/user1/media/downloads/movies/Seven.Samurai.1957.mkv` has been moved to `/home/user1/media/movies/Seven Samurai (1957).mkv`

2016-11-27 13:17 ERROR    subtitle_list download-subtitles File /home/user1/media/downloads/movies/Seven.Samurai.1957.mkv does not exist. Removing from list.
```

i should mention that i did slightly change the config here and there so i'm not sure if this issue might be a result of my modifications, or if the issue also exists in the original config...

**Comment by Jonybat** [comment]
Well, all I can say is that it has been working for me. I rarely download subtitles manually.

**Comment by notDavid** [comment]
Okay i'll check out the modifications i made, maybe there's an error in there...
Thanks for your reply :-)

**Comment by notDavid** [comment]
just fyi:
```
subliminal:
  exact_match: yes
  languages:
    - eng
    - nl
```
the problem was that i added a second language (nl) to the subtitles, which apparently confuses Flexget and makes it download no subs at all :'(
The solution was simply to add: "single: no"
```
subliminal:
  exact_match: yes
  single: no
  languages:
    - eng
    - nl
```

**Comment by Jonybat** [comment]
Glad you got it sorted. Thanks for the info ;)
