### ISSUE TITLE
Possible issue with subtitles

### ISSUE THREAD

**Issue by notDavid** [Jonybat/flexget_config#11]
Hi, another question i was wondering about;

in for example the "move-movies" task, flexget first moves/renames the downloaded files and then adds them to the subtitles list.
Subliminal then uses [guessit](http://guessit.readthedocs.io/en/latest/) to guess information from filenames to determine the correct subtitle to download. This information was already lost by the previous rename.

In other words, it seems it would be much more efficient to first download the subtitles, and then move/rename the files afterwards. This would result in less not-matching subtitles being downloaded.

Am i right in assuming this?

**Comment by Jonybat** [comment]
Hi

I didn't know subliminal used guessit, but it doesn't matter because guessit ignores the kind of info that could be useful when finding subtitles (like the release group). 

Also, afaik, the subtitle search is done by file hash. The filename search its a rudimentary search just to filter the results or to give you more options. That's also why there is an exact match option.

**Comment by notDavid** [comment]
> but it doesn't matter because guessit ignores the kind of info that could be useful when finding subtitles (like the release group)

okay thanks for clarifying :) i  saw a `release_group` field in the example at http://guessit.readthedocs.io/en/latest/ so that's why i thought maybe...

PS.
do you happen to know if there's a command line option to show/clear the contents of the 'subtitles' list?

**Comment by Jonybat** [comment]
Last time I checked, the release_group only only worked if the group was the first thing in the filename and enclosed by square brackets. Afaik currently it's only usefull for Anime fansubs. 

As for the subtitles list, I know it was in the works, but I'm not sure if they finished it. Ask cvium
