### ISSUE TITLE
failed: (UndefinedError) 'tvdb_series_name' is undefined

### ISSUE THREAD

**Issue by marine1988** [Jonybat/flexget_config#12]
The fix is add this lines to global config

thetvdb_lookup: yes
require_field: series_name

@Jonybat  [https://github.com/marine1988/flexget-config](my config)

**Comment by Jonybat** [comment]
What issue?

This doesnt make any sense. Adding lookups to global template is not a good idea.

**Comment by christophercook** [comment]
I am also seeing this error for the "move-series" task.

It seems to be resolved by adding the field in the series-metainfo template.

  series-metainfo:
    metainfo_series: yes
    thetvdb_lookup: yes
    require_field: series_name

**Comment by marine1988** [comment]
Exacly @christophercook  i just remove from global and put it there to. please @Jonybat fix your config when you have some time!

**Comment by Jonybat** [comment]
I have never experienced this issue. It could be related with lookup/network errors.

The metainfo_series and thetvdb_lookup automatically populates all the fields that are missing. The only reason to use the require field is if you want a task to explicitly fail if it is missing. Then again, if if you are somehow missing such a basic field like series_name, then you should look at your config/setup.

**Comment by marine1988** [comment]
im having same issue again now :(
