### ISSUE TITLE
Removing a show in trakt doesn't remove it on flexget

### ISSUE THREAD

**Issue by effemmeffe** [Jonybat/flexget_config#13]
I put one show in my series list on trakt, flexget found it and started downloading it.
Then I changed my mind and removed the show from the list on trakt, but I still get the episodes downloaded by flexget.
Which tasks should take care of removing the show in flexget?
What do I search for in the logs?

**Comment by Jonybat** [comment]
The series are configured in the series template with the content of the entry-list trakt-series. This list is populated by the task fill-series-list. This list is cleared and filled on every task run, so what you want should work. The only thing that i can think of is the fact that all api queries are cached for 2 hours by flexget, so it might take up to 2 hours to take effect.

You can see the current contents of trakt-series list with:
`flexget entry-list list trakt-series`

**Comment by effemmeffe** [comment]
Maybe it was the cache, since now the show is gone.
Thanks.
