### ISSUE TITLE
TVDB Issue: Could not get update information from tvdb: Requests to this site (api.thetvdb.com) have timed out recently. Waiting before trying again.

### ISSUE THREAD

**Issue by neilenore** [Jonybat/flexget_config#14]
Hi mate,

Thanks for this config. But I keep on getting warnings like _Could not get update information from tvdb: Requests to this site (api.thetvdb.com) have timed out recently. Waiting before trying again._ from the logs and I don't know what's causing them. Is there a limit for the tvdb API or do I have to login somewhere? Thanks!

**Comment by Jonybat** [comment]
Hey

I started getting this yesterday or so too. Haven't looked into it yet, but it's probably an issue on thetvdb's end. 

A quick Google returned this:
https://m.facebook.com/story.php?story_fbid=10154888342051041&id=236741176040&__tn__=%2As

**Comment by neilenore** [comment]
I was already receiving this error a few times since last month and it got
worse since yesterday. We'll see if it will work out after their fix.
Thanks man! Awesome work!
