### ISSUE TITLE
Error 502 from pirate bay

### ISSUE THREAD

**Issue by marine1988** [Jonybat/flexget_config#15]
hi there is there any way to fix this?

`2017-03-29 13:52
ERROR
discover
download-movies-sd-discover
Error searching with piratebay: RequestException: Requests to this site (thepiratebay.se) have timed out recently. Waiting before trying again.
2017-03-29 13:52
ERROR
discover
download-movies-sd-discover
Error searching with piratebay: RequestException: Requests to this site (thepiratebay.se) have timed out recently. Waiting before trying again.
2017-03-29 13:52
ERROR
discover
download-movies-sd-discover
Error searching with piratebay: RequestException: Requests to this site (thepiratebay.se) have timed out recently. Waiting before trying again.
2017-03-29 13:52
ERROR
discover
download-movies-sd-discover
Error searching with piratebay: RequestException: Requests to this site (thepiratebay.se) have timed out recently. Waiting before trying again.`

**Comment by Jonybat** [comment]
502 is a server error. PB fails very often, its just how it is, nothing to do with flexget or this config.
