### ISSUE TITLE
Renaming files before downloading subtitles

### ISSUE THREAD

**Issue by zilexa** [Jonybat/flexget_config#18]
Your current config.yml will download, move and rename series and movies first, then search for subtitles. This will lead to the obvious issue of not being able to find a matching subtitle, since the series/movies filename is now too generic, does not contain the release group name etc. 
I could be wrong but looking at the priorities, this is how it is done currently.

**Comment by Jonybat** [comment]
Yes, that is how it is currently done. However, subtitle search uses hashes for comparison, so the actual filename doesn't matter. I've been using this for ages and I almost always get synced subs.

**Comment by zilexa** [comment]
Wow I had absolutely no idea it worked like that. I am used to Kodi's own subtitle addon which relies completely on the titles. So all those subtitle websites don't just store subs, also a hash from the video file? That's actually really smart! I just forked your config. Thanks a lot!

**Comment by Jonybat** [comment]
Btw, kodi also matches subs by hash, thats what the SYNC tag means.
