### ISSUE TITLE
When convert_magnet forced fails, torrents are downloaded by libtorrent in Flexget root folder

### ISSUE THREAD

**Issue by zilexa** [Jonybat/flexget_config#23]
When it cannot convert a magnet, it fails (because force=yes) but then "secretly" downloads the file (they are not send to Transmission!), probably via libtorrent. My RPi SD card fills up to the point I cannot do anything anymore. Took me a while to figure out what was happening to my RPI. 

but I wonder how it works for you? Do you have media files in your Flexget root folder?

**Comment by Jonybat** [comment]
No, I never had any downloads in flexget's folder. The only thing related to that is the converted folder, where that plugin downloads the torrent files to. If i had to guess, I'd say it's something to do with versions, especially of you are using raspbian.

**Comment by zilexa** [comment]
I think it's solved, I modified convert_magnets: yes in your generic transmission template. But the download tasks also had their specific template with convert_magnet: yes. 

Changed the generic one back to 'no' and my drive is still clean after couple of days.
