### ISSUE TITLE
"Cannot find any subtitles for now" for every entry since a few days

### ISSUE THREAD

**Issue by zilexa** [Jonybat/flexget_config#24]
`2017-07-24 00:15 INFO     subtitles     download-subtitles Name computed for /media/mydrive/TVshows/The Big Bang Theory/The Big Bang Theory - S10E16 - The Allowance Evaporation - [480p hdtv].mkv was The Big Bang Theory
2017-07-24 00:15 ERROR    entry         download-subtitles Failed The Big Bang Theory - S10E16 - The Allowance Evaporation - [480p hdtv] (cannot find any subtitles for now.)`

I am confident it worked a couple of weeks ago. But it's failing for every entry now. Could it be Opensubtitles.org is the only source that provides hashes? But Opensubtitles now requires a login. 
In Kodi, I never see [SYNC] when I use any other source. 

OR the issue is `Name computed for (..) was The Big Bang Theory`, for some reason subliminal only recognized the series title, nothing else? Not sure why. 

The only thing I changed in your naming scheme: I added `{% if release_group|default(False) %} - [{{release_group}}]{% endif %}` by adding it at to the end in content_filename (transmission-series template) and rename (move task). But this cannot be the cause since it's not working, all filenames end with the quality, no releasegroup is in the name.

**Comment by Jonybat** [comment]
The computed name has always been the name only, afaik. 

Subtitles download has been working for me, but not sure if they are from opensubtitles. I know they added some restrictions, but haven't looked into it. 

I am not aware of the release group variable, but if it is what I'm thinking about, it is only working for anime fansubs releases.

**Comment by zilexa** [comment]
Just noticed the plugin is updated and the config should declare the providers and their authentication info:
https://flexget.com/Plugins/subliminal

Also, I noticed Kodi has trouble with the folder name for each series. For example the series Casual, it recognised it as some 1980s tvshow. Kodi needs the year to be present. So I will modify the config to add the release year to the folder title.
