### ISSUE TITLE
Question regarding config

### ISSUE THREAD

**Issue by lorgas** [Jonybat/flexget_config#27]
What I want to do is to have flexget download all missing episodes from the tv shows in my collection in trakt and also download new episodes once they come out.

I am completly new to this, so I would appreciate any help!

The thing is that I can not use torrent because of my location. So I need to use Jdownloader and direct downloads from pages like zippyshare, mega.nz etc.

I already have created an own config (https://pastebin.com/MJVTTQVv) but I am not sure if I configured the trakt part correctly to download all missing episodes and new ones.

Furthermore I have a second question do you know why my rss search is returning an error?
ERROR    search_rss    Series_Collection_DE_Search Error attempting to get rss for https://scenefiles.to/showRSS?release=&category=TV-German-HD&result=filecrypt&filter=1k&search=SERIESHERE: Internal server exception on task Series_Collection_DE_Search (https://scenefiles.to/showRSS?release=&category=TV-German-HD&result=filecrypt&filter=1k&search=SERIESHERE)

I hope asking this here is okay.

kind regards

**Comment by zilexa** [comment]
You need to use the backfill option of flexget: 
https://flexget.com/Plugins/series/tracking
https://flexget.com/Plugins/next_series_episodes

It is part of my config (which is a fork of Jonybat config) but commented out as I want to keep it optional for whoever needs it: 
https://github.com/zilexa/Flexget-instructions
Check the first template in my config.yml, starts at line 24 with an explanation. That should help you.
