### ISSUE TITLE
Plugin `convert_magnet` cannot be used because dependency `libtorrent` is missing.

### ISSUE THREAD

**Issue by marine1988** [Jonybat/flexget_config#6]
Hi there again did you task download series magnets working good? I keep receiving this error 
`Plugin`convert_magnet`cannot be used because dependency`libtorrent`is missing.`
Is there anyway to fixe it?

**Comment by Jonybat** [comment]
Did you even read the error? You need to install libtorrent...

**Comment by marine1988** [comment]
i do read but i think libtorrent is a plugin from flexget but isn´t what version of libtorrent do you install?

**Comment by Jonybat** [comment]
Libtorrent has nothing to do with flexget or this config. The package you are looking for could be python-libtorrent, libtorrent-rasterbar, or something like that, depending on your distro.

**Comment by marine1988** [comment]
I have debian on raspberry pi 
Em 27/09/2016 18:42, Jonybat <notifications@github.com> escreveu:Libtorrent has nothing to do with flexget or this config. The package you are looking for could be python-libtorrent, libtorrent-rasterbar, or something like that, depending on your distro.
