### ISSUE TITLE
Torrent download files being moved

### ISSUE THREAD

**Issue by hobojoe** [Jonybat/flexget_config#7]
Hi,

First of all I would like to thank you for this config, it seems awesome!

I started using it and everything seems to working fine, except that the downloads are being added to transmission but shortly after the download file seems to get moved to the final destination and the download fails.

See the image below:
![image](https://cloud.githubusercontent.com/assets/1886514/19220934/5870bda8-8e0f-11e6-938e-e5025d997063.png)

It appears to be only occurring to Series, for movies it seems fine.
Can you help me? 
Thanks in advance!

**Comment by Jonybat** [comment]
Hi. You have to set transmission to add "part" to incomplete files.

**Comment by hobojoe** [comment]
Hi Jonybat,

My transmission settings already has the following:
 "rename-partial-files": true,

I believe it is the correct one right?

For the movies I could verify that the files being downloaded have the ".part" on the filename.

Am I missing something?

**Comment by Jonybat** [comment]
Yes, thats it. I have no idea what could be causing it, but i just noticed that the path in the image that you posted has a double slash between the folders. That might be the issue here.

**Comment by marine1988** [comment]
some times it happened with me to Im one raspberry pi 2
