### ISSUE TITLE
Question: Download only next episodes from trakt

### ISSUE THREAD

**Issue by brothell** [Jonybat/flexget_config#9]
Hello, i really like your setup. I would only like to ask you if its possible to set it to download only non-watched episodes on trakt. 

Right now it seems to redownload old episodes S01E01 i've already saw, but i don't have them on disk.

Thanks for help, your time and opinion :)
Boris

**Comment by Jonybat** [comment]
Hi. This config is not prepared for that. See #8

**Comment by brothell** [comment]
Thank you very much for answer! :) 👍🏾
